version: '3.7'

services:
  app:
    build: .
    env_file:
      - docker.env
    volumes:
      - ../myfinance-web-dotnet/:/home/myfinance-web-dotnet/:rw
    expose:
      - 5000
      - 8080
    ports:
      - "8080:8080"
      - "5000:5000"
